spring:
  application:
    name: gateway
server:
  port: 8088
logging:
  level:
    org.springframework.cloud: debug
---
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: test01
          uri: http://www.baidu.com
          predicates:
            - Path=/test01/**
        - id: test02
          uri: http://class.dxy.cn
          predicates:
            - Path=/test02/**
        - id: local
          uri: http://127.0.0.1:8088
          predicates:
            - Path=/clazz/**
            - Path=/article/**


