spring:
  application:
    name: antelope
  datasource:
    url: jdbc:mysql://localhost:3306/antelope?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: dev
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
    mode: HTML
logging:
  level: debug

dubbo:
  enable: true
  application:
    name: antelope
    owner: antelope
  registry:
    address: zookeeper://localhost:2181
    file: dubboCache/antelope_dev
  monitor:
    address: dubbo://localhost:7070
  consumer:
    enable: true
    version: 1.0.0
    group: antelope_dev
    references:
      - interface-class: com.lmy.antelope.service.SysService
        bean-id: sysService
  provider:
    enable: true
    version: 1.0.0
    group: antelope_dev
    services:
      - interface-class: com.lmy.antelope.service.SysService
        ref: sysServiceImpl
