spring:
  application:
    name: antelope-server-business
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      #      defaultZone: http://111.231.85.42:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
server:
  port: 9001

antelope-server-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
server-user2:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule

management:
  endpoints:
    web:
      exposure:
        include: "*"
