spring:
  application:
    name: config-server
  cloud:
    config:
      enabled: true
      label: master
      server:
        default-application-name: config-server
        git:
          uri: https://github.com/yangmeiliang/config-server
          search-paths: antelopeconfig
server:
  port: 20001

